<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-a01110946/blob/main/assignment01_Python-for-Data-Science-IBM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [213]:
print('assignment01_Python-for-Data-Science-IBM for a01110946 and edited in VS Code, and 22')

assignment01_Python-for-Data-Science-IBM for a01110946 and edited in VS Code, and 22


# **Actividad de semana 1 - 2: Python for Data Science (IBM)**
---
# Apuntes
#### Estos son los apuntes que tomé de los primeros tres módulos del curso de Python for Data Sciece (IBM).
---

## Module 1: Python Basics



### Your First Program

In [214]:
print("Hello Python 101")

# Es una buena práctica agregar comentarios a tu código para que sea más fácil de leer y entender. Esto lo hacemos agregando (#) antes de un comentario.

Hello Python 101


In [215]:
#un error de sintaxis es cuando no seguimos las reglas de programación del lenguaje de Python, imprimirá un error de consola; por ej:
#frint("Hello Python 101")

### Types:
*   `int` = Integers
*   `float` = Float
*   `str` = String
*   `bool` = Boolean || True (1) && False (0)

In [216]:
a = type(11)
b = type(21.213)
c = type("Hello Python 101")
print(a, b, c)

<class 'int'> <class 'float'> <class 'str'>


In [217]:
float(2)


2.0

In [218]:
int(1.1)

1

In [219]:

int('1')

1

In [220]:
# no se puede utilizar typecasting para convertir un string a un número si el string no es un número
# int('A')

In [221]:
type(True)

bool

In [222]:
int(True)

1

In [223]:
int(False)

0

In [224]:
bool(1)

True

In [225]:
bool(0)

False

### Expressions and Variables

In [226]:
#34, 60, 16 y 41 son operands; mientaas que los (+) son los operators
34 + 60 + 16 + 41

151

In [227]:
my_variable=1
my_variable:1
my_variable=10
my_variable:10
print(my_variable)

10


### String Operations:
Indexing[#], el # dentro de [] significa el orden del caracter dentro de la palabra. 0 representa el primer dígito, y si el número es negativo, entonces empezamos de atrás hacia adelante, en donde [-1] es el último caracter del string.

Algunos methods importantes:
*   `str.upper()`
*   `str.replace()`
*   `str.find()`
*   `str.len()`

In [228]:
Name = 'Michael Jackson'
Name[0]+Name[-5]

'Mc'

In [229]:
Name = 'Michael Jackson'
Name[0:16]

'Michael Jackson'

In [230]:
Name = 'Michael Jackson'
'My name is ' + Name[0:16]

'My name is Michael Jackson'

In [231]:
Name = 'Michael Jackson'
print('My name is '+Name[0:7]+'\nI am a singer')

My name is Michael
I am a singer


In [232]:
Name = 'Michael Jackson'
Present = 'My name is '+Name[0:7]+'\nI am a singer'
print(Present.upper())

MY NAME IS MICHAEL
I AM A SINGER


---
# Module 2: Python Data Structures

### Lists and Tuples

#### Lists:
Son similares a los Array. Pueden tener elementos repetidos, tienen un órden específico y son mutable. Se representan con [].

#### Tuples:
Similares a Lists, pero son immutable. Se representan con ().

In [233]:
Tuple1 = ("disco", 10, 1.2)
Tuple1[-2]

10

In [234]:
Tuple1 = ("disco", 10, 1.2)
Tuple2 = Tuple1 + ("hard rock", 10)
Tuple2

('disco', 10, 1.2, 'hard rock', 10)

In [235]:
List = ["Michael Jackson", 10.1, 1982]
List[-1]

1982

In [236]:
List = ["Michael Jackson", 10.1, 1982]
List.append(["pop", 20])
List

['Michael Jackson', 10.1, 1982, ['pop', 20]]

### Sets

#### Sets:
Similar a los diagramas de Venn. Union, Intersection, Difference. Solo tienen elementos únicos, no repetidos; pero sus elementos no tienen orden específico, también son mutable. Se representan con {}.

In [237]:
Set1 = {"pop", "rock", "soul", "hard rock", "rock", "R&B", "rock", "disco"}
Set1

{'R&B', 'disco', 'hard rock', 'pop', 'rock', 'soul'}

In [238]:
List = ["Michael Jackson", 10.1, 1982, "MJ", 10.1]
List_to_set = set(List)
print(List_to_set)

{10.1, 'Michael Jackson', 1982, 'MJ'}


In [239]:
set2 = {"disco", "Thriller", 1979}
set_union = Set1.union(set2)
print(set_union)

{'hard rock', 'disco', 'pop', 'soul', 'Thriller', 'rock', 1979, 'R&B'}


### Dictionaries

#### Dictionaries:
`key:value` pair. Son similares a los JSON en estructura/sintxis, también son mutable. Se representan con {}.

In [240]:
{"key1":1,"key2":"2","key3":[3,3,3],"key4":(4,4,4),('key5'):5}

{'key1': 1, 'key2': '2', 'key3': [3, 3, 3], 'key4': (4, 4, 4), 'key5': 5}

In [241]:
DICT={"Thriller":"1982","Back in Black": "1980","The dark side of the moon":"1973","The BodyGuard":"1992"}
DICT

{'Thriller': '1982',
 'Back in Black': '1980',
 'The dark side of the moon': '1973',
 'The BodyGuard': '1992'}

In [242]:
DICT["Thriller"]

'1982'

In [243]:
DICT.keys()

dict_keys(['Thriller', 'Back in Black', 'The dark side of the moon', 'The BodyGuard'])

---
# Module 3: Python Programming Fundamentals

### Conditions and branching:
* *Menor que* (<)
* *Menor o igual que* (<=)
* *Mayor que* (>)
* *Mayor o igual que* (>=)
* *Igual a* (==)
* *No es igual a* (!=)
* *OR* (||) Si cualquiera de los elementos comparados es True, el resultado será * True; solo cuando ambos/todos son False, el resultado será False. 
* *AND* (&&) Si cualquiera de los elementos comparados es False, el resultado será False; solo cuando ambos/todos son True, el resultado será True.
* *if/else* si la primera condicional se cumple, entonces True y se ejecuta la primera función; si no, se ejecuta la segunda función.
* *elif* si la primera condicional se cumple, entonces True y se ejecuta la primar función; si no, se revisa la segunda condicional, si se cumple, entonces se ejecuta la segunda función, si no, se revisa la siguiente condicional, y así sucesivamente; si no se cumple ninguna condicional, se ejecuta la última función.

In [244]:
a=10
a==10

True

In [245]:
a>8

True

In [246]:
a<8

False

In [247]:
a>=10

True

In [248]:
a!=10

False

In [249]:
age=18
if(age>18):
  print("you can enter")
elif(age==18):
  print("go see Pink Floyd")
else:
  print("go see Meat Loaf")
print("move on")

go see Pink Floyd
move on


### Loops:
* *for loops* aplica una función a todos los elementos (o los definidos específicamente en el loop) de un conjunto.
* *while loops* aplica una función a todos los elementos, en un orden específico, hasta que se deje de cumplir una condicional especificada en el while loop.

In [250]:
squares=["red","yellow","green","purple","blue"]
length=len(squares)
for i in range(0,length):
  squares[i]="white"

squares

['white', 'white', 'white', 'white', 'white']

In [251]:
squares=["red","yellow","green"]
for i, square in enumerate(squares):
  print(square)
  print(i)

red
0
yellow
1
green
2


In [252]:
squares=["orange","orange","yellow","green"]
new_squares=[]
i=0
while(squares[i]=='orange'):
  new_squares.append(squares[i])

  i=i+1

new_squares

['orange', 'orange']

### Functions:
* *len*: entrega la cantidad total de elementos de un conjunto/lista.
* *sum*: entrega la suma de dos o más conjuntos/listas.
* *sorted*: te muestra "copia" de una lista, pero de forma ordenada (la lista original se mantiene sin modificaciones).
* *sort* ordena una lista existente, mas no crea una nueva lista, solo ordena la lista especificada.

In [253]:
def add1(a):
    b=a+1
    return b

In [254]:
add1(5)

6

* **def** es un keyword, significa que vamos a definir una función
* **add1** es el nombre de la función
* **(a)** lo que se encuentra dentro de los paréntesis son los parámetros/argumentos/input, puede haber más de un argumento
* **b=a+1** es la operación/code block a ejecutar cuando se llame esta función
* **return b** es el resultado de la función

### Objects and Classes:
Every object has:
* a *type*
* an internal data representation (a blueprint)
* a set of procedures for interacting with the object (*methods*)
An object is an instance of a particular *type*

A *Class* is a custom-made/defined *type* or data structure, which contains *data attributes* and *methods*. Just as with *types*, there can be many instances or Objects of that custom-defined *Class*.

In [255]:
#Create a Class Circle

class Circle(object):
    def __init__(self, radius, color):
      self.radius = radius;
      self.color = color;

* **Class** es un keyword, significa que vamos a definir una Class
* **Circle** es el nombre de la Class
* **(object)** siempre colocamos (object), es el Class parent

* **def __init__(self, argumento1, argumento2)** siempre se coloca esto para definir los argumentos del Class, en donde argumento1 y argumento2 son los argumentos que queremos crear/asignarle al Class
* **self.radius = radius** es un ejemplo de cómo creamos el argumento *radius* en el Class Circle

In [256]:
#### Create an Object/instance of Class Circle
RedCircle = Circle( 10, 'red' )


* **RedCircle** es el nombre del Object/instance
* **Circle** es el constructor, de tipo Class Circle 
* **10** es el valor del argumento radius
* **''red'** es el valor del argumento color

---
# Module 4: Python Programming Fundamentals

### Reading Files with Open:

In [257]:
# File1 = open("/documents/file_with_data.csv", "w")


    * File1 es el objecto del archivo, se le puede asignar cualquier nombre deseado
    * *open* abre un archivo
    * el primer argumento es el path del archivo
    * el segundo argumento es el modo de apertura, tiene dos opciones: "w" o "r", donde "w" significa write y "r" significa read

In [258]:
#File1.readlines()
#file_lines = File1.readlines()
#for line in file_lines:
#print(line)

    * readlines extrae la primera línea del archivo
    * se pueden extraer caracteres especificando el número de caractéres como argumento de readlines, ej:  `File1.readlines[3]` extraerá los primeros 3 caracteres
    * se pueden extraer dierentes líneas del archivo con indexing, ejemplo:  `file_lines[3]`

### Writing Files with Open:
* File1.write("Hello world!")
    * el método `write` escribe al archivo especificado en el objeto
    * Se puede utilizar un `for loop` que escribe los contenidos de una lista a un archivo, por ej:

In [259]:
List = [ "Line1", "Line2", "Line3" ]
for line in List:
                    print(line)
#File1.write(line)
# es importante utilizar el argumento "a" de append, para agregar cada elemento como una nueva lista en el mismo archivo, y no crear un archivo nuevo

Line1
Line2
Line3


### Loading Data with Pandas:
* **pandas** es una librería de Python muy popular para análisis de datos, para utilizar sus funciones, primero se requiere importar la librería utilizando `import pandas`, se tiene como convención darle el alias *pd* (`import pandas as pd`)
* Se utiliza comúnmente para trabajar con "tablas", o datos típicamente encontrados en hojas de cálculo
* uno de los **types** principales de pandas son los **DataFrames** (`df`), que se componen de filas y columnas, como una tabla
* Se puede utilizar el método *.head* para visualizar las primeras cinco filas de un DataFrame
* Se puede utilizar indexing, especificando el nombre de una columna, para crear un nuevo DataFrame con una subsección de otro DataFrame, ej:

In [260]:
#Este es un ejemplo, en donde housing_df es el nombre de la variable que contiene el dataframe, el cual contiene columnas con datos de vivienda
#housing_df = df[['total_houses', 'house_price_value', 'total_bedrooms', 'mean_house_size', 'mean_house_price_value']]

* Para acceder a un elemento (piensa en una celda de Excel) se puede utilizar el método `.ix` (`df.ix`), seguido de indexing, utilizando un par de números enteros en donde el primer valor se refiere al número de fila, y el segundo valor al número de columna (como si fuera un sistema de coordenadas X,Y); ej: `df.ix[3,2]` en donde accederemos al elemento en la cuarta fila (porque la primera fila utiliza el número 0) de la tercera columna (porque la primera columna utiliza el número 0).

In [261]:
print(housing_df.ix[3,2])

NameError: name 'housing_df' is not defined

In [ ]:
#También se puede utilizar el nombre de la columna en el segundo argumento; ej:
print(df.ix[3, 'house_price_value'])

In [ ]:
#Se puede crear una subtabla del dataframe original utilizando indexing; ej:
print(new_df = df.ix[0:2, 0:3])

In [ ]:
#También se puede utilizar el nombre de la columna, con el siguiente formato:
print(new_df = df.ix[0:2, 'total_houses':'total_bedrooms'])

### Working with and Saving Data with Pandas:

In [ ]:
#El método `unique` ayuda a encontar los valores únicos dentro de una columna de un DataFrame; ej:
print(housing_df['total_bedrooms'].unique())

In [ ]:
#También podemos filtrar un DataFrame seleccionando solamente las filas que cumplan con una condición en cierta columna utilizando condicionales booleanas, y asignando a un nuevo DataFrame; por ej:
affordable_housing_df = df[[housing_df['mean_house_price']<=50000]]
print(affordable_housing_df)


Podemos guardar el nuevo DataFrame a un nuevo archivo externo utilizando *.to_csv()*, y especificando el nombre del archivo como argumento; ej: `affordable_housing_df.to_csv('affordable_housing_data.csv')` 


---
# Module 5: Working with Numpy Arrays & Simple APIs

### Numpy 1D Arrays:

In [263]:
import numpy as np

In [264]:
#un numpy array es similar a una lista, tiene un número fijo de elementos y sus elementos son del mismo tipo
a = np.array([0, 1, 2, 3, 4])

Podemos sumar vectores con numpy, se suman dos 1D Arrays (Numpy Series); realizar esta suma con Python sin numpy conllevaría código más elaborado, y numpy es más eficiente en memoria

In [265]:
u = np.array([1, 0])
v = np.array([0, 1])
z = u + v
print(z)

[1 1]


También se pueden restar vectores con numpy, el proceso es el mismo, solo se cambia (+) por (-)

In [266]:
u = np.array([1, 0])
v = np.array([0, 1])
z = u - v
print(z)

[ 1 -1]


También se puede multiplicar un vector utilizando un escalar con numpy:

In [267]:
m = np.array([1, 2])
n = 3*m
#Ambos valores del vector se multiplican por el escalar (en este caso 3), el resultado sería [3, 6]
print(n)

[3 6]


In [268]:
#Se puede utilizar el método `dot` para calcular el producto punto de dos vectores; ej:
u = np.array([1, 2])
v = np.array([3, 2])
z = u.dot(v)
print(z)

7


También se puede sumar un valor constante a un array:

In [270]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr1 = arr+1
print(arr1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [284]:
print(arr.mean())

6.5


### Numpy 2D Arrays:

También se pueden crear arrays de más de una dimensión. Estos se pueden crear a partir de listas:

In [289]:
list = [[11, 12, 13],[21, 22, 23], [31, 32, 33]]
Array_1 = np.array(list)
print(Array_1)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [290]:
# Para conocer la dimensión del array, podemos utilizar ndim:
Array_1.ndim

2

In [291]:
# El método shape nos permite conocer el número de filas y columnas del array:
Array_1.shape

(3, 3)

In [292]:
# El método size nos permite conocer el número de elementos del array:
Array_1.size

9

In [294]:
# Para obtener un elemento específico del array, podemos utilizar el siguiente formato:
Array_1[1,2]
# En donde el primer número corresponde a la fila, y el segundo a la columna.

23

In [297]:
# Podemos sumar arrays del mismo tamaño, y cada elemento se suma con su correspondiente (misma posición) elemento del otro array; ej:
Array_2 = np.array([[41, 42, 43],[51, 52, 53], [61, 62, 63]])
Array_3 = Array_1 + Array_2
print(Array_3)

[[52 54 56]
 [72 74 76]
 [92 94 96]]


In [298]:
# También se puede multiplicar un array utilizando un escalar:
Array_1*2

array([[22, 24, 26],
       [42, 44, 46],
       [62, 64, 66]])

In [301]:
# También se puede multiplicar un array utilizando otro array del mismo tamaño, y cada elemento se multiplica con su correspondiente (misma posición) elemento del otro array; ej:
Array_4 = Array_1 * Array_2
print(Array_4)

[[ 451  504  559]
 [1071 1144 1219]
 [1891 1984 2079]]


### Simple APIs - Part 1:

Un API (Application Program Interface) es un conector que permite comunicar un software con otro, enviando y reicibiendo datos. Los REST (REpresentational State Transfer) APIs se utilizan para enviar y recibir datos por internet. En un REST API, tu programa se llama Client, el API se comunica con un servidor web por medio de internet; enviando un *request* o *input*, y recibiendo un *response* o *output*. Para utilizar los REST APIs y crear una comunicación por medio de internet, se utilizan los métodos HTTP.\

> Algunos de los métodos HTTP más utilizados son **GET**, **POST** o **PATCH**.

Por lo general, estos métodos HTTP van acompañados de un request, el cual conlleva instrucciones en un formato conocido como JSON (JavaScript Object Notation) que es muy similar a un *dict* de Python, también utilizan pares *key:value*. El servidor web que recibe el request hace una operación y regresa un response también en forma de mensaje JSON.\
\
En el video del curso, una vez que recibe el JSON object como response, lo convierte a un dict de Python, y posteriormenta a un Pandas DataFrame, esto facilita el análisis de los datos.


### Certificado del curso:

El certificado del curso (formato PDF) se puede visualizar en la siguiente liga:

https://github.com/PosgradoMNA/actividades-de-aprendizaje-a01110946/blob/main/Python-for-Data-Science-IBM/Certificate%20-%20IBM%20-%20Python%20for%20Data%20Science.pdf